### DB cred
spring.datasource.url=jdbc:postgresql://localhost:5432/kreditcart
spring.datasource.username=root
spring.datasource.password=tooR@OO7
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-init-sql=SET search_path TO kreditcart_inventory_svc,public;

### Flyway config
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=kreditcart_inventory_svc
spring.flyway.baseline-on-migrate=true
spring.flyway.out-of-order=false
logging.level.org.flywaydb=DEBUG

### jpa
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
logging.level.org.hibernate.tool.hbm2ddl=DEBUG
spring.jpa.properties.hibernate.default_schema=kreditcart_inventory_svc
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

### eureka config
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

### redis config
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

### kafka config
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

### swagger
springdoc.api-docs.path=/api-docs

## misc
server.port=8081
spring.application.name=kreditcart-inventory-svc
server.servlet.context-path=/inventory-svc