server:
  port: 8080

spring:
  application:
    name: kreditcart-api-gateway-svc
  cloud:
    gateway:
      routes:
        - id: product-service-public
          uri: lb://KREDITCART-PRODUCT-SVC
          predicates:
            - Path=/product-svc/api/**

        - id: product-service-internal
          uri: lb://KREDITCART-PRODUCT-SVC
          predicates:
            - Path=/product-svc/internal/api/**

        - id: user-service-public
          uri: lb://KREDITCART-USER-SVC
          predicates:
            - Path=/user-svc/api/**

        - id: user-service-internal
          uri: lb://KREDITCART-USER-SVC
          predicates:
            - Path=/user-svc/internal/api/**

        - id: inventory-service-public
          uri: lb://KREDITCART-INVENTORY-SVC
          predicates:
            - Path=/inventory-svc/api/**

        - id: inventory-service-internal
          uri: lb://KREDITCART-INVENTORY-SVC
          predicates:
            - Path=/inventory-svc/internal/api/**

        - id: order-service-public
          uri: lb://KREDITCART-ORDER-SVC
          predicates:
            - Path=/order-svc/api/**

        - id: order-service-internal
          uri: lb://KREDITCART-ORDER-SVC
          predicates:
            - Path=/order-svc/internal/api/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
