server:
  port: 8080

spring:
  application:
    name: kreditcart-api-gateway-svc
  cloud:
    gateway:
      routes:
        - id: product-service-public
          uri: lb://KREDITCART-PRODUCT-SVC
          predicates:
            - Path=/product-svc/api/**

        - id: product-service-internal
          uri: lb://KREDITCART-PRODUCT-SVC
          predicates:
            - Path=/product-svc/internal/api/**

        - id: product-service-docs
          uri: lb://KREDITCART-PRODUCT-SVC
          predicates:
            - Path=/product-svc/swagger-ui/**, /product-svc/api-docs/**

        - id: user-service-public
          uri: lb://KREDITCART-USER-SVC
          predicates:
            - Path=/user-svc/api/**

        - id: user-service-internal
          uri: lb://KREDITCART-USER-SVC
          predicates:
            - Path=/user-svc/internal/api/**

        - id: user-service-docs
          uri: lb://KREDITCART-USER-SVC
          predicates:
            - Path=/user-svc/swagger-ui/**, /user-svc/api-docs/**

        - id: inventory-service-public
          uri: lb://KREDITCART-INVENTORY-SVC
          predicates:
            - Path=/inventory-svc/api/**

        - id: inventory-service-internal
          uri: lb://KREDITCART-INVENTORY-SVC
          predicates:
            - Path=/inventory-svc/internal/api/**

        - id: inventory-service-docs
          uri: lb://KREDITCART-INVENTORY-SVC
          predicates:
            - Path=/inventory-svc/swagger-ui/**, /inventory-svc/api-docs/**

        - id: order-service-public
          uri: lb://KREDITCART-ORDER-SVC
          predicates:
            - Path=/order-svc/api/**

        - id: order-service-internal
          uri: lb://KREDITCART-ORDER-SVC
          predicates:
            - Path=/order-svc/internal/api/**

        - id: order-service-docs
          uri: lb://KREDITCART-ORDER-SVC
          predicates:
            - Path=/order-svc/swagger-ui/**, /order-svc/api-docs/**

        - id: payment-service-public
          uri: lb://KREDITCART-PAYMENT-SVC
          predicates:
            - Path=/payment-svc/api/**

        - id: payment-service-internal
          uri: lb://KREDITCART-PAYMENT-SVC
          predicates:
            - Path=/payment-svc/internal/api/**

        - id: payment-service-docs
          uri: lb://KREDITCART-PAYMENT-SVC
          predicates:
            - Path=/payment-svc/swagger-ui/**, /payment-svc/api-docs/**

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - url: /user-svc/api-docs
        name: User Service
        primaryName: User Service

      - url: /product-svc/api-docs
        name: Product Service
        primaryName: Product Service

      - url: /inventory-svc/api-docs
        name: Inventory Service
        primaryName: Inventory Service

      - url: /order-svc/api-docs
        name: Order Service
        primaryName: Order Service

      - url: /payment-svc/api-docs
        name: Payment Service
        primaryName: Payment Service